### ISSUE TITLE
Insecure Restful Programming Practices

### ISSUE THREAD

**Issue by devcoinfet** [thesqlservant/restful#3]
Hello, nice to meet You I don't mean to nitpick  but it is considered insecure for a few reasons to do authentication via restful API's

$api_response_code = array(
    0 => array('HTTP Response' => 400, 'Message' => 'Unknown Error'),
    1 => array('HTTP Response' => 200, 'Message' => 'OK'),
    2 => array('HTTP Response' => 201, 'Message' => 'Created OK'),
    3 => array('HTTP Response' => 403, 'Message' => 'HTTPS Required'),
    4 => array('HTTP Response' => 401, 'Message' => 'Authentication Required'),
    5 => array('HTTP Response' => 401, 'Message' => 'Authentication Failed'),
    6 => array('HTTP Response' => 404, 'Message' => 'Invalid Request'),
    7 => array('HTTP Response' => 400, 'Message' => 'Invalid Response Format')
);

You almost never want the user to have a vector of attack, and with the fact they can provide auth as a template means were showing people the wrong thing A secure restful API would use a Nonce to authenticate a user where there is a 1:1 relationship so only users know a valid regex pattern of the nonce and if it is not a valid nonce just disregard and ignore.

Nonces are considered a secure alternative.

I'm not saying a nonce on top of the API auth I mean no Auth the API only responds to a valid client nonce

like this 
https://somesite.com/restfulapi.php?nonce=Abcdefgh434343a2A&request=someparam&someparam

Your code is cool don't get me wrong I just figured I'd drop my 2 sense

**Comment by thesqlservant** [comment]
Thanks for your comments! Its been a long time since I did any work on this repository and it does need review. I've made it private until I get a chance to update it.
